### ISSUE TITLE
Refreshing same note unexpected behaviour

### ISSUE THREAD

**Issue by Oblique82** [mgmeyers/obsidian-zotero-desktop-connector#29]
I am using

Header
Annotations
Footer

- and using ZDC to refresh the same note over and over again

not sure if this is expected behaviour but when I do this but this is the result

- the header remains the same (which is correct)
- the footer gets nuked completely - never to return (I would expect this to remain just as the header does)
- ...and the middle file (annotations) keeps getting duplicated over and over again (appended again with each iteration of refresh)

I would expect the annotations (middle part) to get wiped and replaced with the new data per the template

**Comment by mgmeyers** [comment]
@Oblique82 I wrote a little about this in the docs:

> Currently, you are able to define Header, Annotation, and Footer templates. Annotation templates are unique in that any existing exported annotations will not be overwritten. This allows you to edit the annotation markdown and have your changes persist when exporting multiple times. If you don't care about this, you can use just the header template. The same data is available to all templates.

So, it is indeed expected that the output of the annotation template will be copied over. The purpose of this is so you can add additional notes to highlights, or modify the highlight or your comments (for example, adding an obsidian block id). In my template I have this line so that it only outputs new annotations since the last time I exported:

```
{%- set annots = annotations | filterby("date", "dateafter", lastExportDate) -%}
```

What's _not_ expected is that the footer gets nuked. I'm not sure exactly what's going on here, and can't seem to reproduce, but I made a minor modification that may fix this. Can you update and try again?

**Comment by Oblique82** [comment]
ok thanks 

I think this is working as expected now!

**Comment by mgmeyers** [comment]
Ok, feel free to open another issue if you notice anything amiss

**Comment by Oblique82** [comment]
Just on this topic - is it expected that with every new highlight added to the PDF, ALL the old and new annotations are duplicated and copied over - not JUST the new ones?

thanks!


Warm Regards,

Dr Timothy Hall MBBS, BMEDSCI
Director, Professional Integrative Medicine

This email and all attachments are confidential. If you have received this email in error, please contact Professional Integrative Medicine directly on 08 8379 1124. All content copyright Professional Integrative Medicine Pty Ltd.
